entity_to_index = {}

summary_to_entity = {}
summary_to_entity['Shipping Date'] = 'shipped'
summary_to_entity['Results Received/ NRC-PBI LIMS Request #'] = 'received'
summary_to_entity['Project'] = 'project'
summary_to_entity['SFF'] = 'sff'
summary_to_entity['Mid Set'] = 'mid_set'
summary_to_entity['Plate'] = 'plate'
summary_to_entity['MID'] = 'mid'
summary_to_entity['Sample'] = 'sample'
summary_to_entity['Collector'] = 'collector'	
summary_to_entity['Year'] = 'year'
summary_to_entity['Month'] = 'month'
summary_to_entity['Day'] = 'day'
summary_to_entity['Week'] = 'week'
summary_to_entity['Year_Week'] = 'year_week'
summary_to_entity['Location'] = 'location'
summary_to_entity['City'] = 'city'
summary_to_entity['Province'] = 'province'
summary_to_entity['Crop'] = 'crop'
summary_to_entity['Source'] = 'source'
summary_to_entity['Treatment'] = 'treatment'
summary_to_entity['Substrate'] = 'substrate'
summary_to_entity['Target'] = 'target'
summary_to_entity['Forward Primer'] = 'primer_forward'
summary_to_entity['Reverse Primer'] = 'primer_reverse'
summary_to_entity['PCR Type'] = 'pcr_type'
summary_to_entity['Taq*'] = 'taq'
summary_to_entity['Purification'] = 'purification'
summary_to_entity['Rep #'] = 'rep_num'
summary_to_entity['Cycle #'] = 'cycle_num'
summary_to_entity['DNA Dil'] = 'dna_dil'
summary_to_entity['Annealing'] = 'annealing'
summary_to_entity['DNA_amount_plate_ug'] = 'dna_ug'
summary_to_entity['Notes'] = 'notes'
summary_to_entity['Sequencing_Notes'] = 'sequencing_notes'
summary_to_entity['Max_Temperature_C'] = 'tm_c_max'
summary_to_entity['Min_Temperature_C'] = 'tm_c_min'
summary_to_entity['Average_Temperature_C'] = 'tm_c_avg'
#summary_to_entity['Heat_Degree_Days_C'] =
#summary_to_entity['Cool_Degree_Days_C'] =
#summary_to_entity['Total_Rain_mm'] =
#summary_to_entity['Total_Snow_cm'] =
#summary_to_entity['Total_Percipitation_mm'] =
#summary_to_entity['Snow_on_the_Ground_cm'] =
#summary_to_entity['Wind_Direction_Degrees_from_North'] =
#summary_to_entity['Max_Wind_Speed_km_per_h'] =
#summary_to_entity['Latitude'] =
#summary_to_entity['Longtitude'] =
#summary_to_entity['Elevation_m'] =
#summary_to_entity['Climate_ID'] =
#summary_to_entity['WMO_ID'] =
